services:
  - type: web_service
    name: train-notifier
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn notify_train:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SEND_ONLY_ON_CHANGE
        value: true
      - key: STATE_FILE_PATH
        value: train_state.json
